version: '3'

services:
  formio:
    image: unfao/formio
    build: .
    env_file:
      - ./.env
    ports:
      - '${PORT}:80'
    restart: unless-stopped

networks:
  default:
    external:
      name: '${NETWORK}'
    